<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg"> Ladies and gentlemen, welcome to the second day for doctors for COVID ethics gold standard symposium. We\'re going to start off this morning talking about something that came up a lot when we were covering both health and economics yesterday. And that is the propaganda matrix. And I\'m delighted to be joined by a wonderful group of journalists and publishers, people, and one academic people who know journalism and know communications. So let me just introduce you to our four panelists. First, we have and I have to thank him, Brian, I have to thank you for UK columns role in putting on this gold standard symposium. We have Brian garish, who after a successful career in the Royal Navy, Navy decided to do something about what was going on in the world. And the next thing he did was he discovered himself as a publisher in the media business.</p><p class="serif lh-lg"> And then we have Taylor hudak, who joined us last night as a moderator. Today, she\'s with us as a panelist, and she is one of those up and coming young journalists who\'s really doing amazing things on several websites, one in Munich, and then the American arts, the last vagabond, I believe, and, and Taylor has served doing communications for the doctors of COVID ethics, and so has a very unique perspective. We\'re also joined by Professor Michael Meyer, from the mind from the University of Munich. He says he\'s from academia. But I also know he has a little bit of journalistic experience in his background, but he\'s going to bring a more, I would say, a higher minded perspective, the rest of us are in the trenches. And then we have Patrick henningsen, from 21, at 21st century wire, who also does a show with UK column news and has a long and very distinguished career covering international politics, geopolitics, and I think has a very good sort of overview of the whole situation anyway. So ladies and gentlemen, welcome.</p><p class="serif lh-lg"> I\'m going to start off by asking each of you to make a three and a half minute statement. And then we\'re going to have a bit of a response in a discussion. And, Brian, again, special thanks to you for your role in making this symposium possible. So let\'s start off with you. Well, thank you, thank you very much for inviting me and giving me this opportunity to speak were shorter time. So I\'m going to go very quickly. But I\'m going to say that for the last 10 years in particular, we\'ve been looking at something we think very dangerous unfolding in UK and that\'s the use of applied behavioral psychology in order to get political agendas through. This has now culminated in in the fact that we\'ve we\'ve had all of the chaos surrounding the COVID-19 policy in the lockdown and the resulting so called vaccination policy, that\'s all been happening. But we\'ve kept our eye very much on what\'s been happening with applied behavioral psychology. Now, a few people have used the term propaganda, they say that what we\'re seeing around the psychology is propaganda. That is, that\'s true. But we\'ve got to go deeper. And we\'ve actually got to be considering that the British government and this is this extends worldwide but if I just focus on the UK at the moment, we\'re talking about the use of psychology on the wider public but also on people in positions of authority. So within the local government councils in UK, within the police within education, even the members of parliament themselves have been subjected to this very pernicious applied behavioral psychology. Now, the oranges of this go back many, many years, we can go back to Tavistock, the Tavistock Institute, the Frankfurt School even, we can be looking into the 1930s 1940s. But essentially the period where we began to see this on the rise, we\'re looking around about the year 2000 when we started to see people coming close to British government, in order to advise them on how to use psychology to get political agendas through. And interestingly the first department it affected was the Department for environment and Rural Affairs. That was when we had another so called pandemic of foot and mouth. 11 million animals very cruelly killed.</p><p class="serif lh-lg"> But the Behavioural Insights Team inside that department spread across government became the Behavioural Insights Team alongside the Cabinet Office in UK. And then what have we seen over recent years, we\'ve seen the experts inside that bit team behavioral insight team, working with, amongst others, the French. And we particularly tracked a gentleman called Olivier earlier, who was part of salt cozies inner circle. And there were a number of meetings set up where British and French experts met to join to discuss how they were going to get applied behavioral psychology working both in the UK and in France. Now, where does that take us? That takes us to the fact that we can now show we can prove there\'s no theory here, that the Applied Psychology has been brought directly into all matters to do with COVID. And the vaccine. And the worst example I can give our audience today is the minutes from 22nd of March last year from the government scientific team called the sage team in which they were discussing using fear using stress and anxiety in order to get people in the UK to adhere more to the government\'s COVID-19 policies. So they were going to use fear. And they were also going to turn community members against each other in order to use the community relationships for people to police each other, either by encouragement or by criticism. So that is the situation as we speak in UK, Applied Psychology, the public completely unaware of it, the British government boasting that it can change the way people think, without them understanding what\'s happening. It even says in its 2010 document mindspace people may know their behavior is being changed, but they won\'t know how we\'re if they realize it\'s being changed, they still won\'t fully understand how it was done. This is now expanded across Europe, and the technologies been sold to the US and Australia. This is the danger not just COVID and vaccination, but applied political psychology alongside it.</p><p class="serif lh-lg"> Thank you very much, Brian. Let\'s turn now to Professor mind. Your perspective as someone looking at this from the academic and the research side from the University.</p><p class="serif lh-lg"> I\'m delighted to be here, and especially delighted with the title of this panel. Again, the matrix is a title of my new book published last week. So it\'s the right place to be for today. I have just two points. First, why did state and commercial media defines the reality of the pandemic, not alternative media? And second, why do we not have any false state journalism beyond independent platforms like UK column, vida journalists follow governments using Applied Psychology this was a binds point point right now, my first points in media reality of the pandemic. The traditional media BBC, for example, as a memory of society, the shared backhaul knowledge. Alternative Media, like UK column are not part of CES knowledge, even this conference will not become part of it.</p><p class="serif lh-lg"> That means nobody has to care what we talk about here as long as we not reach the level of key media, like BBC of traditional media. Using King media people observe power relations, who has the power to define reality, with the power to shape society\'s knowledge. So people don\'t have to believe in key media reality is enough to believe in key media effects. In my academic discipline and communication, we talk about influence of presumed influence, influence of presumed influence. This concept has three pillars first, people know that everybody else knows about media reality, knowledge of society. Second, people believe in media effects and serve because of one and two people adapt to King media\'s reality. That\'s what we could observe in the corner cases. In Germany we had and we have a very uniform reporting in the key media. It\'s all about the killer viral story. Some critics say we would have no pandemic without the tests, I say we would have no pandemic</p><p class="serif lh-lg"> Make this key media journalists doing their job. The job of journalism is not to promote government policy. Quite the opposite.</p><p class="serif lh-lg"> By the journalism fair, my second point it\'s I think it\'s all about dependencies about economic and political dependencies. He media are among the winners of the pandemic. First, they got new financial resources, state subsidies and Romney paid ads, lots of ex pregnancy audience came back. In an age of fear and anxiety. People seek safety in official holds official knowledge in official news. And last but not least, as a government\'s help to fight challenges, especially alternative media, blocking channels, deleting videos, freezing bank accounts, observing free and independent journalists via the Secret Service, source and power started the kind of cyber war in order to suppress all non hegemonic information. And in this work, he media a very powerful ally. The lessons that we have to have to learn this is my final sentence is quite simple. We need media without commercial and political dependencies are nonprofit organizations with transparency, the social monitoring is a different media ethics. It\'s a long way, of course, and I think we have to start the public debate on media ownership as a today\'s and tomorrow\'s. Thank you.</p><p class="serif lh-lg"> Thank you. That\'s a book I\'m ordering. That Frick. Thank you. Thank you, Katherine. Just to follow on from what my other panel colleagues said, I\'d like to comment on the coordinated fashion of, of the propaganda that we were witnessing, it\'s coordinated globally. The streamlining of the messaging, even the policy itself, the attacks against dissenters, the fact checkers that have been deployed the deep platforming, by Silicon Valley by big tech. This is like a war effort, and it\'s in its global context is totally unprecedented in history, even to the point now, where the media is working with government institutions to effectively single out and marginalize, quote, anti vaxxers as a kind of crude pejorative term, in particularly vicious fashion. So what started off as ostensibly a sales and marketing campaign for the transnational pharmaceutical, industry or cartel, if you will, has accelerated into something much more pernicious. And, you know, accusing, for instance accusing the quote unvaccinated as being akin to murders as the US President Joe Biden had recently said in commented, the or California Governor Gavin Newsom, comparing the unvaccinated to drunk drivers as a public health hazard. So this is the sort of hyperbolic language that\'s being effectively weaponized. Through propaganda from the government media complex, I say government media complex, because these two institutions are working hand in glove and across borders now. And they\'ve effectively polarized society in recent months. And at worse, the segregating a minority in a manner reminiscent of some of the worst periods of recent history, particularly mid 20th century, Germany, as an example, or in a sectarian country as extreme sectarian or tribal divides. So throughout this shameful saga, the mainstream media has been an enabler and has shown little restraint in attacking those who are considered dissident to government policy. So by combining forces directly between government and the press, the fourth estate has effectively become a fifth column, which is being weaponized against against the people themselves. And if you want to look at the actual data of this, it\'s very clear now, the the drop in advertising just in the UK alone, during the first lockdown, something like a loss of 1.1 billion pounds in advertising spend across all the major industries. And that was really picked up by the government itself, who then became the biggest advertiser. As Michael has commented previously, during that period, almost 50% more than the next biggest corporate spender, which was Unilever.</p><p class="serif lh-lg"> Corporation. And so in addition to this, this was a effectively propaganda campaigns paid for by the government subsidizing all of the mainstream media, mainstream corporate media outlets. And the government struck a 119 million pound deal for COVID advertising weeks before the first lockdown. That\'s according to the UK Daily Telegraph newspaper, that was reported in October of 2020. So there was an advanced plan, if you will, to roll out this propaganda, which as Brian garish, previously commented is, is predicated on weaponized applied behavioral psychology. So, UK Government pandemic advertising in 2020, alone, it tops a quarter of a billion pounds. So this is not these are not trivial sums of money, and some of the worst type of propaganda you\'ve ever seen a very manipulative, definitely attacking the disposition of members of the public, coordinated across every outlet. In terms of messaging, you can just look at a few examples, pick out any day of the year, and you\'ll see completely streamline messaging across all media outlets. The public has never had to face anything like this in history, not in the West, anyway. And to top it off, if you want to look at the civil society sector, the Bill and Melinda Gates Foundation,</p><p class="serif lh-lg"> Corporation. And so in addition to this, this was a effectively propaganda campaigns paid for by the government subsidizing all of the mainstream media, mainstream corporate media outlets. And the government struck a 119 million pound deal for COVID advertising weeks before the first lockdown. That\'s according to the UK Daily Telegraph newspaper, that was reported in October of 2020. So there was an advanced plan, if you will, to roll out this propaganda, which as Brian garish, previously commented is, is predicated on weaponized applied behavioral psychology. So, UK Government pandemic advertising in 2020, alone, it tops a quarter of a billion pounds. So this is not these are not trivial sums of money, and some of the worst type of propaganda you\'ve ever seen a very manipulative, definitely attacking the disposition of members of the public, coordinated across every outlet. In terms of messaging, you can just look at a few examples, pick out any day of the year, and you\'ll see completely streamline messaging across all media outlets. The public has never had to face anything like this in history, not in the West, anyway. And to top it off, if you want to look at the civil society sector, the Bill and Melinda Gates Foundation, up to June 2020. And ploughed something like $250 million in foundation grants into mainstream media outlets, like the BBC, NBC AlJazeera, pro publica, The Guardian Univision, financial times the Atlantic just to name only a few. So this adds another feature to the propaganda rollout, the complete coordination and this is the same Bill and Melinda Gates Foundation that is subsidizing the r&d for the vaccine development. And has marshaled one particular project, I believe that\'s the Oxford vaccine or the AstraZeneca vaccine, but is subsidizing effectively global manufacturing. So there, there is a conflict of interest there on a level that is even on comprehensible. And just to round this off, this crisis is being articulated in a national security context, more and more now we hear the rhetoric. So it\'s worth pointing out that the g7 nations in June of 2018, had initiated what is called the rapid response mechanism, the RRM. And this is an agreement between all g7 nations that they will be of single mind that there\'ll be a single messaging in any particular crisis, that there will be no variations from their agreed narrative. This is the rapid response mechanism. This was initiated by then Prime Minister Theresa May, and this is covering the g7 nations, this is initially said to counter Russian disinformation at the time or enemy disinformation or propaganda. But now we can see that this is exactly what has happened throughout the duration of the COVID crisis. So that that brings it into a geopolitical context to show the level of coordination is unprecedented. And it\'s global. In that respect.</p><p class="serif lh-lg"> Patrick, thank you, they always say follow the money. What we heard yesterday, again, was this notion of plans being made well before the beginning of the pandemic, and in many different fields. So these are serious questions about the propaganda matrix. So now Taylor return to you. Take it away.</p><p class="serif lh-lg"> Thank you for having me. It\'s a pleasure to be here. Now, it is, of course, the role of the media to hold power to account and to hold the establishment to account. And unfortunately, what we are seeing here with this covid 19 crisis is that the media in particular, the mainstream media is doing the groundwork and the PR for the pharmaceutical industry, as well as the corrupt public health industry. And what I find extremely problematic here is that, as we all know, sitting here on this panel, it is our job as media professionals to basically inform the public and our duty is to the public. Instead, our associates I guess, in the mainstream media are encouraging people to make an irreversible health decision, and they\'re only providing them certain types of information in one side of the story here. And so that\'s why it is so important that independent media really plays a strong role.</p><p class="serif lh-lg"> And uplifting the voices of the doctors who are part of say doctors for COVID ethics and those who are speaking out. And I\'ll get to that in just a little bit here. But we know that the propaganda is unfortunately quite effective. One thing to remember is that just a year and a half ago, we did not know the terms PCR test or flatten the curve or social distancing. So we see these public health terms and phrases being used in everyday vernacular, again, pointing to how strong this propaganda is.</p><p class="serif lh-lg"> And of course, the media has been instilling fear in the public, and the media propaganda has also caused people to become fearful of one another, and to also police each other. This is very problematic as it is very reminiscent of what we have seen in the past with totalitarian regimes, and also to it creates a social hierarchy. as Patrick henningsen was saying, the mainstream media is demonizing unvaccinated people blaming the so called surgeon COVID cases and hospitalizations on unvaccinated people. And essentially, those who are vaccinated are becoming fearful of those who choose not to get the job. So we\'re seeing this division. And it\'s important to also remember that the establishment benefits from our division.</p><p class="serif lh-lg"> And again, I\'m sorry.</p><p class="serif lh-lg"> Okay. And again, I want to also emphasize the importance of the doctors who we have really relied on here to provide us with the facts and the science and the truth when it comes to COVID-19. The vaccines and this particular virus, because many of them are demonized in the media. And it reminds me of many of the whistleblowers who speak out john Kiriakou spoke out against the CIA and so many others. And what happens to them is that they are demonized, they are smeared and it comes to a great risk to not only their careers and their personal lives, to speak out and provide us with the truth. So I do want to thank the doctors and medical professionals associated with doctors for COVID ethics, it\'s been my pleasure to work alongside all of you. And I could tell you that each week, each of these doctors are risking so much again to provide us with the truth and the facts here. And again, it\'s been my pleasure to be a part of this. And I just would encourage everybody that\'s independent media is the future. So that\'s the positive here. More and more people are turning away from the mainstream media, the viewership has declined quite significantly over the past 10 years. And specifically, within the past five years, people are also turning to social media to receive their news, which does somewhat tie into independent media. But again, it goes back to the funding model, independent media is funded by viewers Well, the establishment media, mainstream media is funded by the very people that they are meant to hold to account. So I think that the future can look bright if we put more of a focus on independent media, and also more importantly, uplift the voices of the brave men and women in the medical profession who have spoken out against this medical tyranny.</p><p class="serif lh-lg"> So that leads right into my first question, and I\'m gonna throw this out for response, raise your hand if you want to go and I\'ll acknowledge you. So Professor myon said that the I forget your exact words, but that our reality matrix is being is being created by the propaganda matrix, not by independent media. So if independent media is going to get back in the game, what is it we can do to better serve our audience and help them transform away from the situation and the tyranny that is threatening all of us?</p><p class="serif lh-lg"> Anyone who wants to take that? Patrick?</p><p class="serif lh-lg"> I\'ll have a stab at that. You have to Katherine, that\'s a that\'s a really difficult question. You know, one of the big fundamental problems with the current situation, in terms of social media platforms dominating and hoovering up a large percentage of the online traffic is while the mainstream media why governments are seem to be, you know, seem to be rooting out this scourge of disinformation, as they call it, or misinformation, as YouTube, and Google often referred to it or Facebook, there is a lot of misinformation that is circulating even in alternative media, in on social media as well to just to add a little more complication to the mix. So within the independent media, there\'s that problem that people have to contend with as well. But I think people our viewers are more discerning than ever. And this this crisis has forced a lot of people in in many ways is raised</p><p class="serif lh-lg"> The standard of analysis, a recent MIT report where they sent undercover researchers into the quote, alternative media found that there\'s a higher standard of data integrity. And following the facts within the quote, skeptics community, as they, as they said, is opposed to what they would call the mainstream audiences. So that\'s definitely a positive development. So in many ways, people are being forced to be more discerning and to raise their game. So that to me is very promising. And it only means that things are going to open up more and more in the independence sphere and more quality content, hopefully is going to move into that, that space as well.</p>',
          'article_section' => 'health',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Covid-19 Sympsium',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Covid-19 Sympsium',
          'headline_dashed' => 'covid-19-symposium',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1583324113626-70df0f4deaab?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGNvdmlkJTIwMTl8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'health',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Masks are toxic if worn in prolonged periods of time',
          'headline_dashed' => 'masks-are-toxic-if-worn-in-prolonged-periods-of-time',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1602542165989-999c53234fdd?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTV8fGNvdmlkJTIwMTl8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'health',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Covid-19 Vaccines are dangerous and potentially lethal',
          'headline_dashed' => 'covid-19-vaccines-are-dangerous-and-potentially-lethal',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1605377347958-e8bd4c00ba1d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fGNvdmlkJTIwMTl8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'world',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'The story of Israel and the experimental vaccines',
          'headline_dashed' => 'the-story-of-israel-and-the-experimental-vaccines',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1599340695274-f8a2f344174d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGlzcmFlbHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'world',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'WHO - Making a case for institutional capture',
          'headline_dashed' => 'who-making-a-case-for-institutional-capture',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/WHO_flag.png/1920px-WHO_flag.png',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'media',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Fearmongering. The mainstream media\'s favorite tool',
          'headline_dashed' => 'fearmongering-the-mainstream-medias-favorite-tool',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1584359983106-ef9366f27454?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fG5ld3N8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'law',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Reading up on your inalienable human rights',
          'headline_dashed' => 'reading-up-on-your-inalienable-human-rights',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1589578527966-fdac0f44566c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmlnaHRzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'media',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'The fight against caricatures',
          'headline_dashed' => 'the-fight-against-caricatures',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1601319759324-f311bd99ebb9?ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODl8fHRydW1wJTIwZG9sbHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'media',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Throwing mud and hoping that it sticks',
          'headline_dashed' => 'throwing-mud-and-hoping-that-it-sticks',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1581358316909-6d4035624967?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bXVkfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'technology',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => '\'Standing at the gates of hell\': State of the Covid-19 Passports',
          'headline_dashed' => 'standing-at-the-gates-of-hell-state-of-the-covid-19-passports',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1613388395752-a4f8730271e2?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fHBhc3Nwb3J0fGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'world',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Civil discourse collapse',
          'headline_dashed' => 'civil-discourse-collapse',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://images.unsplash.com/photo-1490349708435-19d432984978?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjIyfHx0YWxraW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
          'time_required' => 1,
        ]);

        \App\Models\Article::factory()->create([
          'dateline' => 'Copenhagen, Denmark. August 1st 2021',
          'article_body' => '<p class="serif lh-lg">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
          'article_section' => 'health',
          'word_count' => 42,
          'about' => 'A symposium concerning Covid-19 was held July 31st, 2021.',
          'abstract' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'accountable_person' => 'Daniel Ran Lehmann',
          'alternative_headline' => 'Masks are toxic if worn in prolonged periods of time',
          'audience' => 'Citizens of the world',
          'author' => 'Daniel Ran Lehmann',
          'creative_work_status' => 'published',
          'creator' => 'Daniel Ran Lehmann',
          'credit_text' => 'Credits goes to UK Column, for hosting this symposium.',
          'date_published' => now(),
          'headline' => 'Robert F. Kennedy Jr. and Childrens Health Defense',
          'headline_dashed' => 'robert-f-kennedy-jr-and-childrens-health-defense',
          'in_language' => 'en-US',
          'location_created' => 'Copenhagen, Denmark',
          'maintainer' => 'Daniel Ran Lehmann',
          'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
          'thumbnail_url' => 'https://storage.googleapis.com/afs-prod/media/4a3c4bb9d7514199be28d05f457207b5/3000.jpeg',
          'time_required' => 1,
        ]);
    }
}
